export type SentimentCategory = "positive" | "negative" | "neutral";

// Émotions brutes du CSV (`sentiment_original`) mappées vers 3 catégories
// simples, pour un calcul temporaire en attendant l'activation de la
// classification IA (voir ai-sentiment-analysis). Best-effort : le CSV
// source porte ~190 émotions fines, beaucoup ambiguës ou thématiques
// (ex. "Ambivalence", "Ocean's Freedom") — celles-ci retombent sur
// "neutral" par défaut plutôt que d'être devinées au hasard.
const POSITIVE_LABELS = new Set([
  "acceptance",
  "accomplishment",
  "admiration",
  "adoration",
  "adventure",
  "affection",
  "amazement",
  "amusement",
  "appreciation",
  "awe",
  "blessed",
  "breakthrough",
  "calmness",
  "captivation",
  "celebration",
  "celestial wonder",
  "charm",
  "compassion",
  "compassionate",
  "confidence",
  "confident",
  "connection",
  "contentment",
  "coziness",
  "creative inspiration",
  "creativity",
  "culinary adventure",
  "culinaryodyssey",
  "dazzle",
  "ecstasy",
  "elation",
  "elegance",
  "empowerment",
  "enchantment",
  "enjoyment",
  "enthusiasm",
  "euphoria",
  "excitement",
  "festivejoy",
  "free-spirited",
  "freedom",
  "friendship",
  "fulfillment",
  "grandeur",
  "grateful",
  "gratitude",
  "happiness",
  "happy",
  "harmony",
  "heartwarming",
  "hope",
  "hopeful",
  "inspiration",
  "inspired",
  "joy",
  "joy in baking",
  "joyfulreunion",
  "kind",
  "kindness",
  "love",
  "marvel",
  "motivation",
  "nature's beauty",
  "optimism",
  "overjoyed",
  "playful",
  "playfuljoy",
  "positive",
  "positivity",
  "pride",
  "proud",
  "radiance",
  "rejuvenation",
  "relief",
  "renewed effort",
  "romance",
  "runway creativity",
  "satisfaction",
  "serenity",
  "solace",
  "success",
  "thrill",
  "thrilling journey",
  "touched",
  "tranquility",
  "triumph",
  "vibrancy",
  "whimsy",
  "winter magic",
  "wonder",
  "wonderment",
  "zest",
]);

const NEGATIVE_LABELS = new Set([
  "anger",
  "anxiety",
  "apprehensive",
  "bad",
  "betrayal",
  "bitter",
  "bitterness",
  "boredom",
  "desolation",
  "despair",
  "desperation",
  "devastated",
  "disappointed",
  "disappointment",
  "disgust",
  "dismissive",
  "embarrassed",
  "emotionalstorm",
  "envious",
  "envy",
  "exhaustion",
  "fear",
  "fearful",
  "frustrated",
  "frustration",
  "grief",
  "hate",
  "heartache",
  "heartbreak",
  "helplessness",
  "hostility",
  "intimidation",
  "isolation",
  "jealous",
  "jealousy",
  "loneliness",
  "loss",
  "lostlove",
  "melancholy",
  "miscalculation",
  "negative",
  "overwhelmed",
  "regret",
  "resentment",
  "ruins",
  "sad",
  "sadness",
  "shame",
  "sorrow",
  "suffering",
]);

export function mapOriginalSentimentToCategory(raw: string | null): SentimentCategory | null {
  const normalized = raw?.trim().toLowerCase();
  if (!normalized) return null;
  if (POSITIVE_LABELS.has(normalized)) return "positive";
  if (NEGATIVE_LABELS.has(normalized)) return "negative";
  return "neutral";
}
